In [2]:
#pip install keras

     ---------------------------------------- 1.7/1.7 MB 3.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
#pip install tensorflow

     -------------------------------------- 266.3/266.3 MB 9.8 MB/s eta 0:00:00
     ------------------------------------- 439.2/439.2 kB 26.8 MB/s eta 0:00:00
     ---------------------------------------- 124.6/124.6 kB ? eta 0:00:00
     ---------------------------------------- 6.0/6.0 MB 16.7 MB/s eta 0:00:00
     ------------------------------------- 896.1/896.1 kB 28.6 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 3.1 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 46.1 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 34.3 MB/s eta 0:00:00
     --------------------------------------- 14.2/14.2 MB 36.4 MB/s eta 0:00:00



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 93.3/93.3 kB ? eta 0:00:00
     ------------------------------------- 781.3/781.3 kB 48.2 MB/s eta 0:00:00
     ---------------------------------------- 177.0/177.0 kB ? eta 0:00:00
     ---------------------------------------- 155.3/155.3 kB ? eta 0:00:00
     -------------------------------------- 77.1/77.1 kB 846.9 kB/s eta 0:00:00
     -------------------------------------- 151.7/151.7 kB 9.4 MB/s eta 0:00:00


In [14]:
from keras.datasets import mnist
import numpy as np
import tensorflow as tf
import pandas as pd
import os
import csv
from sklearn.model_selection import train_test_split

#path_photos = '../../archive/img_align_celeba/img_align_celeba'
#path_labels = '../../archive/list_attr_celeba.csv'

path_photos = 'Ressources_Test\images'
path_labels = 'Ressources_Test\img_attributes.csv'

labels_dic = pd.read_csv(path_labels)
#print(labels_dic)
y = []

for row in labels_dic.iterrows():
    #print("row",row[1][0])
    sub_y = []
    for i in range(1,len(row[1])) :
        sub_y.append(row[1][i])
    #print(sub_y)
    y.append(sub_y)

#print(y)
"""
(x_train, y_train), (x_test, y_test) = mnist.load_data(path='../../archive/img_align_celeba/img_align_celeba')


x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
"""

x = []


for filename in os.listdir(path_photos):
    
    f = os.path.join(path_photos, filename)
    # checking if it is a file
    if os.path.isfile(f):
        #print(f)
        image = tf.keras.preprocessing.image.load_img(f)
        input_arr = tf.keras.preprocessing.image.img_to_array(image)
        size = (150, 150)
        new_arr = tf.image.resize(input_arr, size)
        #print("image to array : ",input_arr)
        
        x.append(new_arr)
        

#input_arr = np.array([input_arr])  # Convert single image to a batch.
#print("convert to batch", input_arr)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33)

#x_train = x_train / 255.
#x_test = x_test / 255.

#print('x data shape: ', x)
#print('y data shape: ', y)

x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

print(x_train)
print('Training data shape: ', x_train.shape)
print('Testing data shape : ', x_test.shape)
print('Training labels shape: ', y_train.shape)
print('Testing labels shape : ', y_test.shape)
print(y_train)



[[[[  5.          4.          2.       ]
   [  5.          4.          2.       ]
   [  5.          4.          2.       ]
   ...
   [ 27.666626   26.666626   24.666626 ]
   [ 32.879944   32.59993    33.479874 ]
   [ 34.         34.         36.       ]]

  [[  5.          4.          2.       ]
   [  5.          4.          2.       ]
   [  5.          4.          2.       ]
   ...
   [ 27.666626   26.666626   24.666626 ]
   [ 32.879944   32.59993    33.479874 ]
   [ 34.         34.         36.       ]]

  [[  5.          4.          2.       ]
   [  5.          4.          2.       ]
   [  5.          4.          2.       ]
   ...
   [ 27.666626   26.666626   24.666626 ]
   [ 32.879944   32.59993    33.479874 ]
   [ 34.         34.         36.       ]]

  ...

  [[ 19.600006   11.134224   16.307554 ]
   [ 19.600006   13.733337   18.       ]
   [ 17.733341   12.457781   16.662222 ]
   ...
   [  6.4622164   5.4622164  11.462216 ]
   [  5.426697    5.1466827   6.826767 ]
   [  4.8666687 

In [16]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.layers import Conv2D, MaxPooling2D
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json
from keras import backend as K

In [19]:
# The known number of output classes.
num_classes = 10

# Input image dimensions
img_rows, img_cols = 150, 150


# Channels go last for TensorFlow backend
x_train_reshaped = x_train.reshape(x_train.shape[0], img_rows, img_cols, 3)
x_test_reshaped = x_test.reshape(x_test.shape[0], img_rows, img_cols, 3)
input_shape = (img_rows, img_cols, 3)

print(len(x_train_reshaped))

# Convert class vectors to binary class matrices. This uses 1 hot encoding.
y_train_binary = keras.utils.to_categorical(y_train, num_classes)
y_test_binary = keras.utils.to_categorical(y_test, num_classes)

print(y_train[0])
print(y_train_binary[0])

670
[-1  1  1 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1
  1  1 -1  1 -1 -1 -1 -1  1 -1 -1 -1  1  1 -1  1]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0

In [90]:
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same', input_shape=(28, 28, 3)))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10)

Epoch 1/10


ValueError: in user code:

    File "C:\Users\fifid\anaconda3\lib\site-packages\keras\engine\training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\fifid\anaconda3\lib\site-packages\keras\engine\training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\fifid\anaconda3\lib\site-packages\keras\engine\training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\fifid\anaconda3\lib\site-packages\keras\engine\training.py", line 1023, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\fifid\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\fifid\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_3" is incompatible with the layer: expected shape=(None, 28, 28, 3), found shape=(None, 218, 178, 3)
