In [2]:
#pip install keras

     ---------------------------------------- 1.7/1.7 MB 3.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
#pip install tensorflow

     -------------------------------------- 266.3/266.3 MB 9.8 MB/s eta 0:00:00
     ------------------------------------- 439.2/439.2 kB 26.8 MB/s eta 0:00:00
     ---------------------------------------- 124.6/124.6 kB ? eta 0:00:00
     ---------------------------------------- 6.0/6.0 MB 16.7 MB/s eta 0:00:00
     ------------------------------------- 896.1/896.1 kB 28.6 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 3.1 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 46.1 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 34.3 MB/s eta 0:00:00
     --------------------------------------- 14.2/14.2 MB 36.4 MB/s eta 0:00:00



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 93.3/93.3 kB ? eta 0:00:00
     ------------------------------------- 781.3/781.3 kB 48.2 MB/s eta 0:00:00
     ---------------------------------------- 177.0/177.0 kB ? eta 0:00:00
     ---------------------------------------- 155.3/155.3 kB ? eta 0:00:00
     -------------------------------------- 77.1/77.1 kB 846.9 kB/s eta 0:00:00
     -------------------------------------- 151.7/151.7 kB 9.4 MB/s eta 0:00:00


In [21]:
from keras.datasets import mnist
import numpy as np
import tensorflow as tf
import pandas as pd

path_photos = '../../archive/img_align_celeba/img_align_celeba'
path_labels = '../../archive/list_attr_celeba.csv'
labels_dic = pd.read_csv(path_labels)
#print(labels_dic)

"""
(x_train, y_train), (x_test, y_test) = mnist.load_data(path='../../archive/img_align_celeba/img_align_celeba')


x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
"""

image = tf.keras.preprocessing.image.load_img('../../archive/img_align_celeba/img_align_celeba/000001.jpg')
input_arr = tf.keras.preprocessing.image.img_to_array(image)
print("image to array : ",input_arr)

#input_arr = np.array([input_arr])  # Convert single image to a batch.
#print("convert to batch", input_arr)

#x_train = x_train.astype('float32') / 255.
#x_test = x_test.astype('float32') / 255.

"""
print('Training data shape: ', x_train.shape)
print('Testing data shape : ', x_test.shape)
"""


image to array :  [[[253. 231. 194.]
  [253. 231. 194.]
  [253. 231. 194.]
  ...
  [247. 226. 225.]
  [254. 238. 222.]
  [254. 238. 222.]]

 [[253. 231. 194.]
  [253. 231. 194.]
  [253. 231. 194.]
  ...
  [249. 228. 225.]
  [254. 238. 222.]
  [254. 238. 222.]]

 [[253. 231. 194.]
  [253. 231. 194.]
  [253. 231. 194.]
  ...
  [250. 231. 227.]
  [255. 239. 223.]
  [255. 239. 223.]]

 ...

 [[140.  74.  26.]
  [116.  48.   1.]
  [146.  78.  33.]
  ...
  [122.  55.  28.]
  [122.  56.  30.]
  [122.  56.  30.]]

 [[130.  62.  15.]
  [138.  70.  23.]
  [166.  98.  53.]
  ...
  [118.  49.  20.]
  [118.  51.  24.]
  [118.  51.  24.]]

 [[168. 100.  53.]
  [204. 136.  89.]
  [245. 177. 132.]
  ...
  [118.  49.  20.]
  [120.  50.  24.]
  [120.  50.  24.]]]


"\nprint('Training data shape: ', x_train.shape)\nprint('Testing data shape : ', x_test.shape)\n"

In [ ]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json
from keras import backend as K

In [ ]:
# The known number of output classes.
num_classes = 10

# Input image dimensions
img_rows, img_cols = 28, 28

# Channels go last for TensorFlow backend
x_train_reshaped = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test_reshaped = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

# Convert class vectors to binary class matrices. This uses 1 hot encoding.
y_train_binary = keras.utils.to_categorical(y_train, num_classes)
y_test_binary = keras.utils.to_categorical(y_test, num_classes)

In [ ]:
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same', input_shape=(64, 64, 3)))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10)